### ISSUE TITLE
NEW person: Rosie Schrag

### ISSUE THREAD

**Issue by jillfreitas** [virtualredhead/red.staff#1]
![rosie](https://user-images.githubusercontent.com/25016552/39822864-b1ab267a-5379-11e8-9337-62320e5ffa57.jpg)

Creating is my therapy, it always has been. I love getting lost in all the small details of each piece I create. I've been drawing since I was a little girl. I would often drive myself to the point of frustrated tears over a drawing not looking how I wanted it to. Since then, I've developed a healthier process, but I still value feeling discontentment with my work;  it drives me forward.

In high school, I had the opportunity to experiment with a lot of different visual mediums ranging from metals to painting to experimental film photography. This led me on a natural path to graphic design in college. I have an associate's degree from Washtenaw Community College. I bounced between a couple of schools before I got there, but I ended up choosing it because I felt the program had the most bang for its buck. I knew I would continue learning and pushing myself outside of school because creating things is basically a compulsion for me. 

To me, the most important qualities to bring to the design process are empathy and curiosity. Powerful design speaks directly to the heart of the audience. I'm an avid believer in being genuine, which I think is part of the reason I was drawn to Redhead. As an artist and designer, I feel I have a responsibility to use this form of communication to further the greater good. And here at Redhead, I get to do that. 

I love bourbon, black coffee and all things green. If I'm not designing or doodling, I'm probably adventuring outdoors somewhere or sitting in the corner of a coffee shop with my nose in a book.

**Comment by jakejohns** [comment]
Need:
- title
- role
