### ISSUE TITLE
URGENT: IMMEDIATE ATTENTION REQUIRED

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.staff#15]
![HBD-Jake](https://user-images.githubusercontent.com/38866201/81410330-8844c780-910e-11ea-9165-e0816fb43163.jpg)

**Comment by Rachak66** [comment]
HABBY BIRZDEY!
https://www.youtube.com/watch?v=Yns80o2ETAg

**Comment by allisonraeck** [comment]
@jakejohns HBD JAKE! i attached this as a png and not a jpeg just for you on your special day.
![image](https://user-images.githubusercontent.com/38868589/81408823-f045de80-910b-11ea-8cd2-59c7cd3237fe.png)

**Comment by jenestill** [comment]
I think we need to add some dates. 
![unnamed-1](https://user-images.githubusercontent.com/11651042/81410645-1456ef00-910f-11ea-9b48-b96d9d042fa8.jpg)

**Comment by jenestill** [comment]
HBD friend!
