### ISSUE TITLE
NEW person: Allison Raeck

### ISSUE THREAD

**Issue by jillfreitas** [virtualredhead/red.staff#2]
![allison](https://user-images.githubusercontent.com/25016552/39822976-00b4dc20-537a-11e8-8357-0d2bd18092f1.jpg)

My name is Allison and I love to write.

From long-form articles to sarcastic tweets, I find myself constantly bouncing between writing projects (whatever the length). As an odd kid who loved the smell of new books and could meander stationery stores for hours in search of a good gel pen, I always knew I would do something in the creative writing realm down the line.

To me, effective writing captures a specific voice. I try to carefully curate each word with purpose, so the piece matches a specific client's tone or attitude. Just like a chameleon blending into leaves and things. One word can change the entire direction of a project, so I make the most of every syllable. My writing process involves lots of research, sporadic creative streaks, and countless searches on thesaurus.com. And, of course, strong coffee.

I earned my bachelor's in communications at the University of Michigan, with minors in business and writing. There, I diversified my writing portfolio, edited countless intro-English essays as a side job, and even struggled through a few accounting classes. My career path search wound around from journalism to film but, regardless, I knew writing would play a role in whatever I did. (Well, maybe aside from that brief pre-dentistry stint.) 

After graduation I settled on public relations and moved to Chicago. The land of wind, hot pretzels, and a bean. I worked at a public relations firm there for two years, where I got to know the inner-workings of agency life and collaborate with clients in the tech industry. I also got to live in a "charming vintage" apartment from the 1920s, where it is rumored that Al Capone used to converse with sketchy individuals in the penthouse (fun fact). I loved the city but, after two years, I decided it was time to come back to the Lansing area to be closer to my family (and to work at Redhead, of course). 

Aside from writing, I'm an avid crafter, reality TV-watcher and bargain hunter with a passion for cats.

**Comment by jakejohns** [comment]
Need:
- title
- role
