### ISSUE TITLE
headshots!

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.staff#27]
add new + replace Jen's

![caleb](https://github.com/virtualredhead/red.staff/assets/38866201/209d9bf9-1ede-47a9-abcc-a9bc37cc5559)
![jen](https://github.com/virtualredhead/red.staff/assets/38866201/d4f03d75-ceab-4d65-a183-4601186ccd4a)
![moe](https://github.com/virtualredhead/red.staff/assets/38866201/49d15306-1e58-4bc4-8f60-c8c1fe673258)
![kate](https://github.com/virtualredhead/red.staff/assets/38866201/f0fa23d2-5422-4ab2-b8ee-e446fd1eff40)

**Comment by tonybredhead** [comment]
Updated
