### ISSUE TITLE
Add photo/bio for Bobby Earls

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.staff#6]
![Bobby](https://user-images.githubusercontent.com/38866201/65334169-e0cf5080-db8f-11e9-88d2-bc1da14cb081.jpg)

Hey there, I'm Bobby. 

While the rest of the team is working on the frontlines to meet deadlines and woo clients, I'm working behind-the-scenes to keep this wonderful creative machine well-oiled and sharp. You could call me the jack-of-all-trades and you wouldn't be wrong. Important deliveries, office supplies, and general support—you got it. You'd be surprised what I do to keep this hardworking team fueled and (relatively) sane. Creative output needs a little crazy, after all.

Working here at Redhead seems as fateful as anything. I'm an Old Town resident so it's tough to spin when I'm late, but the craziest thing involves my cat, Louise. Louise is a bonafide local legend. People started to notice when she would join my dogs on their walks, sporadically diving into bushes but always keeping up. Turns out Redhead's fancy was tickled, too. They grew so fond of Louise that they created an internal zine in her name—all before I started working here.

But just like the rest of Redhead, I'm no stranger to creativity. Before my time here I studied interior design at Lansing Community College and worked at a studio in SoHo, NYC. I came back to Michigan because I missed my roots and needed to expand them, but I never stopped flexing my creative muscles. While I'm passionate about the arts in general, I really love to craft, plant, and bake (cinnamon rolls are my specialty). To me, creativity is the ability to imagine something and bring it to fruition and that's exactly what we do here at Redhead.

After hours you can find me walking the river trail with my dogs or exploring one of the many local events.

**Comment by Rachak66** [comment]
Title: Executive Assistant

Role: Organization, Coordination
