### ISSUE TITLE
Add photo/bio for Lynn Morris

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.staff#7]
![Lynn](https://user-images.githubusercontent.com/38866201/65334250-0b210e00-db90-11e9-8a36-4e407658111c.jpg)

One day, years back, I really wanted to learn how to juggle. So I did. I practiced and practiced until I was pretty good, but sadly I never went professional. I could do it while riding a bike, too.

Today, my juggling looks a little different; I have two kids, a full-time job as a designer here, and a part-time woodworking business. The busiest days help me appreciate living on a lake and the ability to escape life's stresses on my boat.

I majored in graphic design with a minor in communications at Saginaw Valley State University and have been creating ever since. My professional background consists of designing apparel, magazines, advertisements, mobile apps, and UI/UX for websites and web applications—just to name a few things.

Here at Redhead, I'm surrounded by creatives and people who thoroughly understand the design process. This makes my job more enjoyable because I can bounce ideas off of everyone and receive constructive feedback from every desk in the office. A thoroughly collaborative environment is essential to excellent design, and that's a big part of why I love coming into work every morning.

Creativity is everywhere. It's when I'm in my workshop finding the right wood for a coffee table, designing a new website at work, or playing LEGOs® with my kids. Creativity doesn't always mean reinventing the wheel, either. Many times it means finding a new angle or an interesting, yet smart, twist on things. It's an enticing challenge and one that I love to pursue.

When my right-brain is resting, I like to check out historic architecture and landmarks around Lansing. Like I said, creativity is everywhere.

**Comment by Rachak66** [comment]
Title: Designer

Role: Creative problem solving, user experience
