### ISSUE TITLE
Add photo/bio for Zachary Komorowski

### ISSUE THREAD

**Issue by RosieSchrag** [virtualredhead/red.staff#8]
![Zach](https://user-images.githubusercontent.com/38866201/65334307-27bd4600-db90-11e9-8bb6-9116828ea463.jpg)
Hey, I’m Zach, lover of em-dashes and oxford commas. And I guess I’m a creative.
 
But I didn’t always think that. When I was about 13 years old my life plan was to become a neurosurgeon, “make bank” for five or so years, and retire to live out the rest of my days in a hammock somewhere. I thought I had hacked the system. Well, by the time I was gearing up to start college I realized that this plan, while ambitious, probably wasn’t going to happen. I pursued computer science until I realized I’d rather write words than code. So here I am, savoring my time at Michigan State University while working towards a B.A. in creative advertising and a sidecar minor in computer science.
 
Writing has always intrigued me. The first story I remember penning was about a penguin who wore a tuxedo. Contrived, derivative, cliché—it was terrible. I don’t think it even had a plot. I’ve improved a bit since then and lately I’ve been writing poetry and craft beer reviews while violently bouncing between short stories. Over the years my friends have repeatedly asked me to write their Instagram captions or Facebook event descriptions so joining the marketing/communications space was my way of saying, "Sorry guys, I don't work for free."
 
Creativity is all about being a good listener. Listening sparks ideas, often from unexpected people, places, and sources. Understanding that everyone has something to contribute enables an empathetic mind, something that is paramount when writing to connect with people—especially in this industry. Here at Redhead I get to write things, problem-solve things, research things, and—most importantly—learn things. All in Old Town, Lansing. Pretty neat.

When my pen is capped you can find me brewing my own beer, reading a book, or well into the REM stage.

**Comment by Rachak66** [comment]
Title: Creative Intern

Role: MSU, Degree Expected December 2020
